/**
 * All the words the UI says: tips, disclaimer, SlopBot lines, combo shouts, quips.
 * Tone: PG slapstick + heartwarming + self-aware AI-slop jokes (target the slop, never people).
 */
import { shuffle } from './dom';

/** Deliberately terrible AI-generated tips. */
export const SLOP_TIPS = [
  'Tip: Jimothy has eleven fingers. (Source: an AI)',
  'Tip: Raccoons are a type of cloud. Press W to precipitate.',
  'Tip: This tip was generated. We apologize.',
  'Tip: Certainly! Here is a tip: tip.',
  'Tip: To wash an item faster, simply become water.',
  'Tip: Studies show 9 out of 10 raccoons. The tenth one is Jimothy.',
  'Tip: Jimothy is perfectly spherical. The legs are a rendering error. Do not measure him.',
  'Tip: If you are reading this, the tip is working as intended.',
  'Tip: The Space Noodle is 100% real noodle. Do not eat the Space Noodle.',
  'Tip: Trash cans contain trash. Sometimes they contain more trash.',
  'Tip: Crows remember faces. They also remember what you did.',
  'Tip: As a large language raccoon, I cannot give tips. Here are 4 tips.',
  'Tip: Press Jump to jump. Press Jump twice to jump once, but emotionally.',
  'Tip: Salmon swim upstream because downstream is full of Slopothys.',
  'Tip: Rolling downhill is faster than rolling uphill. We checked. Twice.',
  'Tip: Loading tips… loading tips… this tip is about loading.',
];

/** Honest tips (controls & mechanics). `{action}` tokens become key chips where rendered. */
export const REAL_TIPS = [
  'Real tip: hold {wash} near water to wash whatever you are holding.',
  'Real tip: press {roll} to tuck into a ball. Downhill is your best friend.',
  'Real tip: hold {jump} against walls, trees and poles to climb. Watch your stamina.',
  'Real tip: chain silly acts within 3 seconds to build a combo multiplier.',
  'Real tip: press {objectives} to see your Instincts. Completing them unlocks Mutators.',
  'Real tip: {grab} grabs small things, drags big things, and steals phones.',
  'Real tip: {bonk} while carrying something throws it. Aim with the camera.',
  'Real tip: press {chitter} to chitter. Fans love it.',
];

export const WILDLIFE_TIP = 'Real tip: never feed wild raccoons. Admire Jimothy from a distance.';

/** Tip order: shuffled slop with real tips sprinkled in, wildlife note early. */
export function tipSequence(): string[] {
  const slop = shuffle([...SLOP_TIPS]);
  const real = shuffle([...REAL_TIPS]);
  const out: string[] = [];
  let r = 0;
  for (let i = 0; i < slop.length; i++) {
    out.push(slop[i]);
    if (i % 2 === 1 && r < real.length) out.push(real[r++]);
    if (i === 2) out.push(WILDLIFE_TIP);
  }
  while (r < real.length) out.push(real[r++]);
  return out;
}

export const TAGLINE = "He's round. He's real. He's washing your phone.";

export const DISCLAIMER =
  'Jimothy Simulator was made in one night by an AI while its human slept. It is held together with duct tape, ' +
  'vibes and several thousand lines of load-bearing slop. Anything that looks like a bug is an emergent raccoon ' +
  'behavior. If Jimothy clips through a wall, that is canon now. The real Jimothy is a wild animal: admire him from ' +
  'a distance, never feed him, and do not hand him your phone. He will wash it.';

export const PAUSE_QUIPS = [
  'Jimothy is paused. He remains round.',
  'Time has stopped. The trash can wait. (It cannot.)',
  'Paused. Somewhere, a phone is still dirty.',
  'Even cryptids need a snack break.',
  'Enhance… enhance… still a raccoon.',
  'This pause was generated by an AI. It is 100% pause.',
  'Jimothy is thinking about bagels.',
];

export interface SlopLine {
  text: string;
  /** Label of the "yes" button. */
  gen: string;
  /** What SlopBot says after you click it. */
  result: string;
}

export const SLOPBOT_LINES: SlopLine[] = [
  {
    text: "It looks like you're trying to be a raccoon! Would you like me to generate a raccoon instead?",
    gen: 'Generate 12 raccoons',
    result: 'Done! I generated 12 raccoons. Eleven have too many legs and one is a bagel. You’re welcome!',
  },
  { text: "I've summarized this trash can: it is trash.", gen: 'Summarize it again', result: 'Updated summary: it is still trash, but now with synergy.' },
  {
    text: "As an AI, I can't wash things. But I can generate a picture of washing!",
    gen: 'Generate washing.png',
    result: 'Here is your picture of washing: [image unavailable]. It is very wet.',
  },
  {
    text: 'Did you know? Raccoons have eleven fingers. I double-checked with myself.',
    gen: 'Add more fingers',
    result: 'Fingers added. Jimothy now has “a lot”. Please do not count them.',
  },
  {
    text: 'You seem round. Would you like me to optimize your shape? (Enhanced by AI™)',
    gen: 'Optimize me',
    result: 'Optimization complete: you are now 4% rounder. Circles everywhere are jealous.',
  },
  {
    text: "I noticed you've been rolling. Have you considered rolling… with AI?",
    gen: 'Roll with AI',
    result: 'Rolling with AI is now enabled. Nothing changed, but it costs $20 a month.',
  },
  {
    text: 'Your free trial of Reality expires in 3 days. Upgrade to Reality Pro™?',
    gen: 'Upgrade Reality',
    result: 'Reality upgraded. Colors are now 12% more saturated. Side effects may include fish.',
  },
  {
    text: "I can't let you bonk that, Jimothy. Just kidding. I don't know what bonking is.",
    gen: 'Explain bonking',
    result: 'Bonking (noun): a type of cloud. Source: me, just now.',
  },
  {
    text: "Hi! I'm SlopBot™. I replaced your hands with more helpful hands. Want more?",
    gen: 'Generate hands',
    result: 'Generated 30 hands. They are holding other hands. It is hands all the way down.',
  },
  {
    text: 'It looks like you’re writing a letter to the City Council! Shall I add the word “delve” 40 times?',
    gen: 'Delve',
    result: 'I delved. It has been delved. Everything is delved now.',
  },
];

/** Combo-end shouts by combo size. */
export function comboWord(combo: number): string {
  const tiers: [number, string[]][] = [
    [20, ['LEGENDARY BALL!', 'CITY COUNCIL IS CONCERNED!', 'HONORARY DEGREE IN CHAOS!']],
    [12, ['CERTIFIED CRYPTID!', 'MAXIMUM ROUNDNESS!', 'WHAT AM I LOOKING AT?!']],
    [8, ['RACCOONTASTIC!', 'TRASH-TACULAR!', 'UNHINGED!']],
    [5, ['STRIKE!', 'ROUND-TASTIC!', 'SPLENDID!']],
    [0, ['NICE!', 'NEAT!', 'OKAY THEN!']],
  ];
  for (const [min, words] of tiers) if (combo >= min) return words[Math.floor(Math.random() * words.length)];
  return 'NICE!';
}

/** Flavor sub-lines for the area banner, matched against area names. */
const AREA_SUBS: [RegExp, string][] = [
  [/slop/i, 'Disrupting raccoons since last Tuesday'],
  [/washing|universit/i, 'Home of the Fighting Raccoons (unofficially)'],
  [/hill|residential/i, 'Steep streets. Premium rolling.'],
  [/gas|pond|park(?!.*tee)/i, 'Mostly gas. Some works.'],
  [/ballard|old /i, 'Where it all began. July 13, 2026.'],
  [/downtown|noodle|city hall/i, 'The Space Noodle is not edible. Probably.'],
  [/lock|ladder/i, 'Salmon go up. Boats go down. Jimothy goes wherever.'],
  [/market|plaice|waterfront|dock|pier/i, 'Fish get thrown here. Catch one.'],
  [/tee-?hee|stadium|ballpark/i, 'Home of the Ballard Barnacles'],
  [/bay|beach|shore/i, 'Wet. Extremely wet.'],
  [/den|thrift|goodwheel/i, 'Mom is home. Probably wants snacks.'],
];
export function areaSubtitle(name: string): string | undefined {
  for (const [re, sub] of AREA_SUBS) if (re.test(name)) return sub;
  return undefined;
}

/** Jimothy's chitter bubbles. */
export const CHITTERS = ['chk chk chk!', '*trill*', 'hrrrm?', 'chirrr!', '*happy noises*', 'chk!'];

